apiVersion: v1
kind: Secret
metadata:
  name: github-token
type: Opaque
data:
  bearerToken: Z2hwX0RCaDgzVFhyZ1FlMjVIOGpKbUI0ZFNsZFNUVVJBRDRQOWJyag==

  ---
  kubectl create secret generic github-token \
  --namespace flux-system \
  --from-literal=username=gexcode \
  --from-literal=password=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
